### ISSUE TITLE
Why retry() does not check "userErrorCb_ != NULL"

### ISSUE THREAD

**Issue by jinq0123** [shinberg/cpp-hiredis-cluster#14]
userErrorCb_ is checked before call:

        if ( that->userErrorCb_ != NULL && that->userErrorCb_(

But retry() doesn't check NULL. Is that OK?

        static void retry( Connection *con, void *r, void *data )
        {
            AsyncHiredisCommand* that = static_cast<AsyncHiredisCommand*>( data );
            
            if( that->processHiredisCommand( con ) != REDIS_OK )
            {
                that->userErrorCb_( *that, DisconnectedException(), HiredisProcess::FAILED );
                that->userCallback_p_( that->cluster_p_, r, that->userPrivData_ );
                delete that;
            }
        }

**Comment by shinberg** [comment]
Hi,
because commandState is set to RETRY only if userErrorCb_ exists and returns RETRY state, see the folowing sources

>

                if ( that->userErrorCb_ != NULL && that->userErrorCb_( *that, ce, state ) == RETRY )
                {
                    commandState = RETRY;
                }
thank you
